users_list:
  controller: Controller\UserController:listUsersAction

user:
  controller: Controller\UserController:showUserAction

add_user:
  controller: Controller\UserController:addUser

add_userinfo:
  controller: Controller\UserController:addUserInfo

add_avatar:
  controller: Controller\UserController:addAvatar

del_user:
  controller: Controller\UserController:deleteUser

log_user:
  controller: Controller\UserController:logUser

logout:
  controller: Controller\UserController:logOut

products_list:
  controller: Controller\ProductController:listProductsAction

product:
  controller: Controller\ProductController:showProductAction

add_product:
  controller: Controller\ProductController:addProduct

del_product:
  controller: Controller\ProductController:deleteProduct

confirm:
  controller: Controller\UserController:confirm