user_list:
  controller: Controller\UserController:listUserAction

user:
  controller: Controller\UserController:showUserAction

adduser:
  controller: Controller\UserController:addUser

deluser:
  controller: Controller\UserController:deleteUser

loguser:
  controller: Controller\UserController:logUser

logout:
  controller: Controller\UserController:logOut